### ISSUE TITLE
The main function has too many bugs. I'm not considering replicating your results; I just hope the code can run normally.

### ISSUE THREAD

**Issue by RuiyuM** [shanshuo/MVT#1]
dataset_train = MVDataSet("", train_txt,
TypeError: __init__() got an unexpected keyword argument 'view_num'

**Comment by shanshuo** [comment]
The `view_num` is defined [here](https://github.com/shanshuo/MVT/blob/main/main.py#L151). In Python, hyphens (-) in the argument names are automatically converted to underscores (_) in the parsed arguments. So you should use `--view-num` in the command line to run.
