### ISSUE TITLE
Pretrained Checkpoint Released

### ISSUE THREAD

**Issue by ALEX13679173326** [shanshuo/MVT#2]
Nice work!!
However, I find no ckpt in this repository. Could you please release your pretrained checkpoint? That might be helpful for me!

**Comment by shanshuo** [comment]
Thanks for your interests in our work. The pre-trained DeiT small model checkpoint could be downloaded [here](https://dl.fbaipublicfiles.com/deit/deit_small_patch16_224-cd65a155.pth).
